stages:
  - build_dev
  - deploy_dev
  - build_prod
  - deploy_prod

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'

build_manual:
  stage: build_dev
  image: repo.ozonedev.ir/base/docker:26.1-dind
  tags:
    - dev-builder
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" repo.ozonedev.ir
    - docker image rmi --force repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8} || true
    - docker image rmi --force repo.ozonedev.ir/dev/new-front/app:latest || true
  script:
    - cp ${dev_env} .env
    - if [ ! -f ./deployment/Dockerfile ]; then echo "Dockerfile not found"; exit 1; fi
    - |
      docker build \
        --build-arg NEXT_PUBLIC_ENVIROMENT=develop \
        --build-arg NODE_ENV=develop \
        -f ./deployment/Dockerfile \
        -t repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8} \
        -t repo.ozonedev.ir/dev/new-front/app:latest \
        .
    - docker push repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8}
    - docker push repo.ozonedev.ir/dev/new-front/app:latest
  when: manual
  only:
    - merge_requests
  allow_failure: false

build_automatic:
  stage: build_dev
  image: repo.ozonedev.ir/base/docker:26.1-dind
  tags:
    - dev-builder
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" repo.ozonedev.ir
    - docker image rmi --force repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8} || true
    - docker image rmi --force repo.ozonedev.ir/dev/new-front/app:latest || true
  script:
    - cp ${dev_env} .env.production
    - if [ ! -f ./deployment/Dockerfile ]; then echo "Dockerfile not found"; exit 1; fi
    - |
      docker build \
        --build-arg NEXT_PUBLIC_ENVIROMENT=develop \
        --build-arg NODE_ENV=develop \
        -f ./deployment/Dockerfile \
        -t repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8} \
        -t repo.ozonedev.ir/dev/new-front/app:latest \
        .
    - docker push repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8}
    - docker push repo.ozonedev.ir/dev/new-front/app:latest
  only:
    - develop
  allow_failure: false

deploy_dev:
  stage: deploy_dev
  image:
    name: repo.ozonedev.ir/base/devops/bitnami/kubectl:1.29.4
    entrypoint: ['']
  tags:
    - dev-builder
  before_script:
    - ls
  script:
    - kubectl --kubeconfig=$dev_kubeconfig -n oc-dev-app set image deployment oc-dev-app oc-dev-app="repo.ozonedev.ir/dev/new-front/app:${CI_COMMIT_SHA:0:8}"
    - kubectl --kubeconfig=$dev_kubeconfig -n oc-dev-app delete po -l project=app,type=client --force || true
  only:
    - merge_requests
    - develop
  except:
    - production

build_prod:
  stage: build_prod
  image: repo.ozonedev.ir/base/docker:26.1-dind
  tags:
    - prod-builder
  before_script:
    - ls -a
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" repo.ozonedev.ir
    - docker image rmi --force repo.ozonedev.ir/prod/new-front/app:latest || true
  script:
    - cp ${prod_env} .env.production
    - docker build \
      --build-arg NEXT_PUBLIC_ENVIROMENT=production \
      --build-arg NODE_ENV=production \
      -f ./deployment/Dockerfile \
      -t repo.ozonedev.ir/prod/new-front/app:${CI_COMMIT_SHA:0:8} \
      -t repo.ozonedev.ir/prod/new-front/app:latest \
      .
    - docker push repo.ozonedev.ir/prod/new-front/app:${CI_COMMIT_SHA:0:8}
    - docker push repo.ozonedev.ir/prod/new-front/app:latest
  only:
    - production

deploy_prod:
  stage: deploy_prod
  image:
    name: repo.ozonedev.ir/base/devops/bitnami/kubectl:1.29.4
    entrypoint: ['']
  tags:
    - prod-deploy
  before_script:
    - ls
  script:
    - kubectl --kubeconfig=$prod_kubeconfig -n prod-app set image deployment prod-app prod-app="reg.o3social.app/prod/new-front/app:${CI_COMMIT_SHA:0:8}"
    - kubectl --kubeconfig=$prod_kubeconfig -n prod-app delete po -l project=app,type=client --force || true
  only:
    - production
  when: manual
