export const QUERY_KEYS = {
  GET_SAMPLE_KEY: 'get-sample-key',
  POST_LOGIN_INIT: 'post-login-init',
  POST_LOGIN_OTP: 'post-login-otp',
  GET_INVOICES_DETAILS: 'get-invoices-details',
  GET_USER_ME: 'get-user-me',
  GET_WALLETS: 'get-wallets',
  GET_WALLETS_INQUIRY: 'get-wallets-inquiry',
  GET_DONUT: 'get-donut',
  GET_INVOICES: 'get-invoices',
  GET_INVOICES_CHART: 'get-invoice-chart',
  GET_WALLET_TRANSACTIONS: 'get-wallet-transactions',
  GET_INIT_PASSWORD: 'get-init-password',
  POST_CHARGE_WALLET: 'post-charge-wallet',
  PATH_WALLET_STATUS: 'patch-wallet-status',
  POST_WALLET_INQUIRY: 'post-wallet-inquiry',
  POST_VERIFY_WALLET_INQUIRY: 'post-verify-wallet-inquiry',
  POST_VERIFY_ADD_WALLET: 'post-verify-add-wallet',
  GET_QR_CODE: 'get_qr_code',
  GET_VOUCHER: 'get_voucher',
  GET_BUSINESSES: 'get_merchantes',
  GET_WALLET_TRANSACTIONS_PAGE: 'get-wallet-transactions-page',
  GET_RECEIPT: 'get-receipt',
};
